import bcrypt from 'bcryptjs';

const hash = (pw) => bcrypt.hashSync(pw, 10);

export const seedUsers = [
  {
    id: 'usr_admin_001',
    name: 'VDORT Admin',
    email: 'admin@vdort.com',
    password: hash('admin123'),
    role: 'admin',
    company: 'VDORT Services Pvt. Ltd.',
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'usr_client_001',
    name: 'Sarah Mitchell',
    email: 'client@vdort.com',
    password: hash('client123'),
    role: 'client',
    company: 'TechCorp Global Inc.',
    createdAt: '2024-03-15T00:00:00.000Z',
  },
  {
    id: 'usr_client_002',
    name: 'James Chen',
    email: 'james@techcorp.com',
    password: hash('client123'),
    role: 'client',
    company: 'FinEdge Solutions',
    createdAt: '2024-06-20T00:00:00.000Z',
  },
];

export const seedJobs = [
  {
    id: 'job_001',
    title: 'Senior React Developer',
    company: 'Top-tier Fintech Company',
    clientId: 'usr_client_001',
    location: 'San Francisco, CA',
    type: 'Full-time',
    experience: '5-8 years',
    salary: '$140K - $180K',
    industry: 'Software Development',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'AWS'],
    status: 'active',
    applicationsCount: 12,
    posted: '2026-06-28T00:00:00.000Z',
    description: 'We are looking for a Senior React Developer to lead frontend architecture for a high-growth fintech platform serving millions of users.',
  },
  {
    id: 'job_002',
    title: 'Cloud Solutions Architect',
    company: 'Global Enterprise Client',
    clientId: 'usr_client_001',
    location: 'Remote (US)',
    type: 'Full-time',
    experience: '8-12 years',
    salary: '$160K - $220K',
    industry: 'Cloud Computing',
    skills: ['AWS', 'Azure', 'Terraform', 'Kubernetes', 'Python'],
    status: 'active',
    applicationsCount: 8,
    posted: '2026-06-29T00:00:00.000Z',
    description: 'Design and implement multi-cloud architecture solutions for Fortune 500 enterprise clients.',
  },
  {
    id: 'job_003',
    title: 'Machine Learning Engineer',
    company: 'AI-first Healthcare Startup',
    clientId: 'usr_client_002',
    location: 'Boston, MA',
    type: 'Full-time',
    experience: '3-6 years',
    salary: '$130K - $170K',
    industry: 'Artificial Intelligence',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'MLOps', 'Computer Vision'],
    status: 'active',
    applicationsCount: 15,
    posted: '2026-06-27T00:00:00.000Z',
    description: 'Build and deploy production ML models for medical imaging diagnosis and patient outcome prediction.',
  },
  {
    id: 'job_004',
    title: 'SAP S/4HANA Consultant',
    company: 'Big 4 Consulting Firm',
    clientId: 'usr_client_002',
    location: 'Chicago, IL',
    type: 'Contract',
    experience: '6-10 years',
    salary: '$85 - $110/hr',
    industry: 'SAP',
    skills: ['S/4HANA', 'SAP FICO', 'ABAP', 'SAP BTP', 'Data Migration'],
    status: 'active',
    applicationsCount: 5,
    posted: '2026-06-25T00:00:00.000Z',
    description: 'Lead SAP S/4HANA migration projects for major enterprise transformations across multiple industries.',
  },
  {
    id: 'job_005',
    title: 'Cybersecurity Analyst',
    company: 'Defense Contractor',
    clientId: 'usr_client_001',
    location: 'Washington, DC',
    type: 'Full-time',
    experience: '3-5 years',
    salary: '$100K - $140K',
    industry: 'Cybersecurity',
    skills: ['SIEM', 'Incident Response', 'Threat Hunting', 'Python', 'CISSP'],
    status: 'active',
    applicationsCount: 9,
    posted: '2026-06-22T00:00:00.000Z',
    description: 'Monitor, detect, and respond to security threats in a critical infrastructure environment.',
  },
  {
    id: 'job_006',
    title: 'Data Engineering Lead',
    company: 'E-commerce Giant',
    clientId: 'usr_client_002',
    location: 'Seattle, WA',
    type: 'Full-time',
    experience: '7-10 years',
    salary: '$150K - $200K',
    industry: 'Data Engineering',
    skills: ['Spark', 'Snowflake', 'Python', 'Airflow', 'dbt'],
    status: 'filled',
    applicationsCount: 22,
    posted: '2026-06-26T00:00:00.000Z',
    description: 'Lead a team of data engineers building real-time data pipelines processing billions of events daily.',
  },
];

export const seedApplications = [
  {
    id: 'app_001',
    jobId: 'job_001',
    jobTitle: 'Senior React Developer',
    name: 'Alex Rivera',
    email: 'alex.rivera@email.com',
    phone: '+1 555-0101',
    experience: '6 years',
    message: 'Passionate React developer with fintech experience.',
    resumeUrl: null,
    status: 'reviewing',
    createdAt: '2026-06-30T10:00:00.000Z',
  },
  {
    id: 'app_002',
    jobId: 'job_002',
    jobTitle: 'Cloud Solutions Architect',
    name: 'Priya Sharma',
    email: 'priya.s@email.com',
    phone: '+91 98765-43210',
    experience: '10 years',
    message: 'AWS certified architect with multi-cloud expertise.',
    resumeUrl: null,
    status: 'shortlisted',
    createdAt: '2026-06-29T14:30:00.000Z',
  },
  {
    id: 'app_003',
    jobId: 'job_003',
    jobTitle: 'Machine Learning Engineer',
    name: 'David Kim',
    email: 'david.kim@email.com',
    phone: '+1 555-0202',
    experience: '4 years',
    message: 'ML engineer specializing in healthcare AI.',
    resumeUrl: null,
    status: 'new',
    createdAt: '2026-07-01T09:15:00.000Z',
  },
];

export const seedContacts = [
  {
    id: 'con_001',
    name: 'Michael Thompson',
    email: 'michael@enterprise.com',
    phone: '+1 555-1000',
    company: 'Enterprise Corp',
    subject: 'IT Staffing Inquiry',
    message: 'Looking for 20+ developers for a 6-month project.',
    type: 'client',
    status: 'new',
    createdAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'con_002',
    name: 'Lisa Wang',
    email: 'lisa.wang@startup.io',
    phone: '+1 555-2000',
    company: 'Startup.io',
    subject: 'Executive Hiring',
    message: 'Need help finding a CTO for our Series B startup.',
    type: 'client',
    status: 'contacted',
    createdAt: '2026-06-28T16:00:00.000Z',
  },
  {
    id: 'con_003',
    name: 'Robert Johnson',
    email: 'robert.j@email.com',
    phone: '+1 555-3000',
    company: null,
    subject: 'Career Inquiry',
    message: 'Interested in career opportunities in cloud computing.',
    type: 'candidate',
    status: 'resolved',
    createdAt: '2026-06-25T11:00:00.000Z',
  },
];

export const seedSubscribers = [
  { id: 'sub_001', email: 'newsletter@example.com', createdAt: '2026-06-20T00:00:00.000Z' },
  { id: 'sub_002', email: 'hr@bigcorp.com', createdAt: '2026-06-22T00:00:00.000Z' },
];

export const seedTestimonials = [
  {
    id: 'tst_001',
    name: 'Jennifer Adams',
    role: 'VP of Talent',
    company: 'TechCorp Global',
    type: 'client',
    rating: 5,
    text: 'VDORT transformed our hiring process. Their AI-powered matching reduced our time-to-hire by 60% while improving candidate quality significantly.',
    image: null,
    featured: true,
    createdAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'tst_002',
    name: 'Marcus Williams',
    role: 'Senior Software Engineer',
    company: 'Placed at Google',
    type: 'candidate',
    rating: 5,
    text: 'The VDORT team understood my career goals perfectly. Within 3 weeks, I had multiple offers from top tech companies. Exceptional service.',
    image: null,
    featured: true,
    createdAt: '2026-02-20T00:00:00.000Z',
  },
  {
    id: 'tst_003',
    name: 'Dr. Ananya Patel',
    role: 'CHRO',
    company: 'HealthFirst Systems',
    type: 'client',
    rating: 5,
    text: 'Finding specialized healthcare IT talent is incredibly challenging. VDORT delivered qualified candidates within days, not months.',
    image: null,
    featured: true,
    createdAt: '2026-03-10T00:00:00.000Z',
  },
];
